### ISSUE TITLE
Upgrade Print class.

### ISSUE THREAD

**Issue by imduchuyyy** [bui-duc-huy/mini-cool-wallet#4]
We need a beautiful print function.

**Comment by imduchuyyy** [comment]
something like "Type" - "Title" - "Message"

**Comment by bxdoan** [comment]
Something like this ?

<img width="406" alt="Screenshot 2022-11-30 at 17 04 10" src="https://user-images.githubusercontent.com/17973436/204767557-448dc95d-8c1d-403b-9702-87714f24a30b.png">

**Comment by imduchuyyy** [comment]
What percent represent for?, but it's look so good

**Comment by bxdoan** [comment]
it is just the `pytest` print out, I will make PR for you see that

**Comment by imduchuyyy** [comment]
many thanks.
